# Generated by Django 4.2.10 on 2024-03-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportCsv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_response_rate', models.IntegerField()),
                ('host_identity_verified', models.IntegerField()),
                ('host_total_listings_count', models.IntegerField()),
                ('city', models.IntegerField()),
                ('is_location_exact', models.IntegerField()),
                ('property_type', models.IntegerField()),
                ('room_type', models.IntegerField()),
                ('accommodates', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('beds', models.IntegerField()),
                ('bed_type', models.IntegerField()),
                ('amenities', models.IntegerField()),
                ('price', models.IntegerField()),
                ('minimum_nights', models.IntegerField()),
                ('number_of_reviews', models.IntegerField()),
                ('review_scores_rating', models.IntegerField()),
                ('instant_bookable', models.IntegerField()),
                ('cancellation_policy', models.IntegerField()),
                ('reviews_per_month', models.IntegerField()),
                ('fraud', models.IntegerField()),
            ],
        ),
    ]
