# Generated by Django 4.2.10 on 2024-03-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importcsv',
            name='accommodates',
            field=models.IntegerField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='importcsv',
            name='amenities',
            field=models.IntegerField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='importcsv',
            name='bathrooms',
            field=models.IntegerField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='importcsv',
            name='bed_type',
            field=models.IntegerField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='importcsv',
            name='bedrooms',
            field=models.IntegerField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='importcsv',
            name='beds',
            field=models.IntegerField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='importcsv',
            name='cancellation_policy',
            field=models.IntegerField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='importcsv',
            name='city',
            field=models.IntegerField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='importcsv',
            name='fraud',
            field=models.IntegerField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='importcsv',
            name='host_identity_verified',
            field=models.IntegerField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='importcsv',
            name='host_response_rate',
            field=models.IntegerField(verbose_name='host_response_rate'),
        ),
        migrations.AlterField(
            model_name='importcsv',
            name='host_total_listings_count',
            field=models.IntegerField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='importcsv',
            name='instant_bookable',
            field=models.IntegerField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='importcsv',
            name='is_location_exact',
            field=models.IntegerField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='importcsv',
            name='minimum_nights',
            field=models.IntegerField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='importcsv',
            name='number_of_reviews',
            field=models.IntegerField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='importcsv',
            name='price',
            field=models.IntegerField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='importcsv',
            name='property_type',
            field=models.IntegerField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='importcsv',
            name='review_scores_rating',
            field=models.IntegerField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='importcsv',
            name='reviews_per_month',
            field=models.IntegerField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='importcsv',
            name='room_type',
            field=models.IntegerField(verbose_name=''),
        ),
    ]
